import axios from 'axios'

const client = axios.create({ baseURL: '/api' })

const _pfx = (projectId) => projectId ? `/projects/${projectId}` : ''

export const listTickets = (projectId) => client.get(`${_pfx(projectId)}/tickets`)
export const getTicket = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}`)
export const getTicketState = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/state`)
export const getTicketLogs = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/logs`)
export const getTicketPlan = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/plan`)
export const getTicketReview = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/review`)
export const getTicketTests = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/tests`)
export const getTicketArtifacts = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/artifacts`)
export const getTicketTimeline = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/timeline`)

export const runNextStep = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/run-next`)
export const approvePlan = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/approve-plan`)
export const requestPlanFix = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/request-plan-fix`)
export const approveImplementation = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/approve-implementation`)
export const requestImplementationFix = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/request-implementation-fix`)
export const commitChanges = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/commit`)
export const pushChanges = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/push`)
export const createCheckpoint = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/checkpoint`)
export const archiveDaemon = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/archive`)
export const getAuditLog = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/audit-log`)
export const markConflictFailed = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/mark-conflict-failed`)
export const resolveConflicts = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/resolve-conflicts`)
export const approveConflictResolution = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/approve-conflict-resolution`)
export const rejectConflictResolution = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/reject-conflict-resolution`)
export const getTicketIntelligence = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/intelligence`)
export const analyzeTicketIntelligence = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/intelligence/analyze`)
export const getTicketReadiness = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/readiness`)
export const postEvaluateReadiness = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/evaluate-readiness`)
export const getTicketApprovals = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/approvals`)
export const approveExecution = (id, projectId, payload) => client.post(`${_pfx(projectId)}/tickets/${id}/approve-execution`, payload)
export const rejectExecution = (id, projectId, payload) => client.post(`${_pfx(projectId)}/tickets/${id}/reject-execution`, payload)
export const getProjectRules = (projectId) => client.get(`/projects/${projectId}/rules`)
export const putProjectRules = (projectId, payload) => client.put(`/projects/${projectId}/rules`, payload)
export const getTicketRuleEvaluation = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/rule-evaluation`)
export const postEvaluateTicketRules = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/evaluate-rules`)
export const getTicketDiagnostics = (id, projectId) => client.get(`${_pfx(projectId)}/tickets/${id}/diagnostics`)
export const runTicketDiagnostics = (id, projectId) => client.post(`${_pfx(projectId)}/tickets/${id}/diagnostics/run`)
