"""Git branch and PR management for AI-generated operational scripts."""
from __future__ import annotations

import datetime
import json
import subprocess
from pathlib import Path


def commit_and_push(project_root: Path, project_id: str) -> tuple[str, str]:
    """Create a branch, commit generated scripts, push, and create/update a PR.

    Returns (branch_name, pr_url).
    """
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch = f"ai-scripts/{project_id}-{ts}"

    _git(["checkout", "-b", branch], project_root)
    _git(["add", ".ai-dev-factory/scripts/", ".ai-dev-factory/deployment.md"], project_root)
    _git(["commit", "-m", "chore: AI-generated operational scripts"], project_root)
    _git(["push", "-u", "origin", branch], project_root)

    pr_url = _create_or_update_pr(project_root, branch)
    return branch, pr_url


def _git(args: list[str], cwd: Path) -> str:
    result = subprocess.run(
        ["git"] + args,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _create_or_update_pr(cwd: Path, branch: str) -> str:
    list_result = subprocess.run(
        ["gh", "pr", "list", "--head", branch, "--json", "url", "--state", "open"],
        cwd=str(cwd),
        capture_output=True,
        text=True,
    )

    if list_result.returncode == 0:
        try:
            prs = json.loads(list_result.stdout)
            if prs:
                pr_url = prs[0]["url"]
                subprocess.run(
                    [
                        "gh", "pr", "edit", pr_url,
                        "--title", "AI-generated operational scripts",
                        "--body", (
                            "Operational scripts generated by AI. "
                            "Review, make executable, and merge when ready."
                        ),
                    ],
                    cwd=str(cwd),
                    capture_output=True,
                    check=True,
                )
                return pr_url
        except (json.JSONDecodeError, KeyError, IndexError):
            pass

    result = subprocess.run(
        [
            "gh", "pr", "create",
            "--head", branch,
            "--title", "AI-generated operational scripts",
            "--body", (
                "Operational scripts generated by AI. "
                "Review, make executable, and merge when ready."
            ),
        ],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()
